# Generated by Django 4.0.2 on 2022-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120)),
                ('employee_desig', models.CharField(max_length=100)),
                ('employee_exp', models.PositiveIntegerField()),
                ('employee_salary', models.PositiveIntegerField()),
            ],
        ),
    ]
